title: Jekyll Theme - Lazy
email: d.k.danailova@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a very minimalistic theme for jekyll done for training purposes.
baseurl: "/theme-lazy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"

twitter_username: jekyllrb
github_username:  ddanailova

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .gitignore
   - scss
   - gulpfile.js
   - package.json
   - package-lock.json

